2022/10/29 14:18:25 [emerg] 1#1: host not found in upstream "host.docker.internal" in /etc/nginx/conf.d/default.conf:8
2022/10/29 14:20:36 [emerg] 1#1: host not found in upstream "host.docker.internal" in /etc/nginx/conf.d/default.conf:8
2022/10/29 14:21:20 [emerg] 1#1: host not found in upstream "host.docker.internal:3333" in /etc/nginx/conf.d/default.conf:2
2022/10/29 14:24:57 [notice] 1#1: using the "epoll" event method
2022/10/29 14:24:57 [notice] 1#1: nginx/1.23.2
2022/10/29 14:24:57 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2022/10/29 14:24:57 [notice] 1#1: OS: Linux 5.10.16.3-microsoft-standard-WSL2
2022/10/29 14:24:57 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/10/29 14:24:57 [notice] 1#1: start worker processes
2022/10/29 14:24:57 [notice] 1#1: start worker process 28
2022/10/29 14:24:57 [notice] 1#1: start worker process 29
2022/10/29 14:24:57 [notice] 1#1: start worker process 30
2022/10/29 14:24:57 [notice] 1#1: start worker process 31
2022/10/29 14:24:57 [notice] 1#1: start worker process 32
2022/10/29 14:24:57 [notice] 1#1: start worker process 33
2022/10/29 14:24:57 [notice] 1#1: start worker process 34
2022/10/29 14:24:57 [notice] 1#1: start worker process 35
2022/10/29 14:24:57 [notice] 1#1: start worker process 36
2022/10/29 14:24:57 [notice] 1#1: start worker process 37
2022/10/29 14:24:57 [notice] 1#1: start worker process 38
2022/10/29 14:24:57 [notice] 1#1: start worker process 39
2022/10/29 14:24:57 [notice] 1#1: start worker process 40
2022/10/29 14:24:57 [notice] 1#1: start worker process 41
2022/10/29 14:24:57 [notice] 1#1: start worker process 42
2022/10/29 14:24:57 [notice] 1#1: start worker process 43
2022/10/29 14:24:57 [notice] 1#1: start worker process 44
2022/10/29 14:24:57 [notice] 1#1: start worker process 45
2022/10/29 14:24:57 [notice] 1#1: start worker process 46
2022/10/29 14:24:57 [notice] 1#1: start worker process 47
2022/10/29 14:25:10 [error] 30#30: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /api/graphql HTTP/1.1", upstream: "http://172.17.0.1:3333/api/graphql", host: "localhost:8443", referrer: "http://localhost:8443/"
2022/10/29 14:25:19 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /api/graphql HTTP/1.1", upstream: "http://172.17.0.1:3333/api/graphql", host: "localhost:8443", referrer: "http://localhost:8443/"
2022/10/29 14:25:27 [error] 30#30: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /api/graphql HTTP/1.1", upstream: "http://172.17.0.1:3333/api/graphql", host: "localhost:8443", referrer: "http://localhost:8443/"
2022/10/29 14:25:32 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /api/graphql HTTP/1.1", upstream: "http://172.17.0.1:3333/api/graphql", host: "localhost:8443", referrer: "http://localhost:8443/"
2022/10/29 14:25:36 [error] 30#30: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "POST /api/graphql HTTP/1.1", upstream: "http://172.17.0.1:3333/api/graphql", host: "localhost:8443", referrer: "http://localhost:8443/"
2022/10/29 14:26:05 [error] 30#30: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "GET /api/ HTTP/1.1", upstream: "http://172.17.0.1:3333/api/", host: "localhost:8443"
